name: calm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  firebase_core: ^3.5.0
  table_calendar: ^3.1.2
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  go_router: ^14.3.0
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  textfield_tags: ^3.0.1
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2

flutter:
  uses-material-design: true
